### ISSUE TITLE
macro compile error

### ISSUE THREAD

**Issue by utkusen** [EmpireProject/Empire#664]
## Empire Version
2.1 (29 August 2017)

## OS Information (Linux flavor, Python version)
Kali Linux 2017.1, Python 2.7

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

TL;DR: Office macro script has a syntax error. Because of that not working.

Attacking machine: Kali Linux 2017.1
Target machine: Windows 7 with Office 2016

There is no communication problem between attacker&target when I use "multi/launcher" or "windows/launcher_bat". But when I use "windows/macro", include it to a Word&Excel file and enabled macro, nothing happens. I tried to trigger the macro by hand, I got following error: https://imgur.com/a/68Fwc

I tried with Obfuscation, without Obfuscation, they all have same error

**Comment by rvrsh3ll** [comment]
yeah I see the issue. Failing macro has single quotes vs double quotes. Looking into this. Thank you.

**Comment by rvrsh3ll** [comment]
Fixed!

**Comment by utkusen** [comment]
@rvrsh3ll Now I don't get any compiling error but macro still not working. I don't see any connection attempt when I listen the traffic with Wireshark. Any ideas?

**Comment by rvrsh3ll** [comment]
Screenshots of your network adapter settings and listener settings please

**Comment by utkusen** [comment]
Well that's weird, when I click "Enable Macros" button nothing happens but if I manually go to Macros tab and run by hand, it works. Probably something with Office 2016 (new update or something), not the Empire.

**Comment by leperjulien** [comment]
Same issue for me , but target is Mac OS with Microsoft Word 2011 , when i enable macro nothing happends ; but i go manually in the macro tab and hit play, an agent will connect back :/
