### ISSUE TITLE
Wrong TLS version protocol in API listener

### ISSUE THREAD

**Issue by crazyrat-software** [EmpireProject/Empire#683]
## Empire Version
Version 2.1

## OS Information (Linux flavor, Python version)
Kali 2017.2
Python 3.5.4

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
DeathStar (https://github.com/byt3bl33d3r/DeathStar) cannot connect to API. Immediate connection error.

## Screenshot of error, embedded text output, or Pastebin link to the error
[*] Powering up the Death Star
[-] Connection Error. Check Empire RESTful API

## Any additional information
After some debugging I've found that the problem lays in the way empire is creating local listener.
current initialization: 
**context = ssl.SSLContext(ssl.PROTOCOL_TLSv1)**

should be:
**context = ssl.SSLContext(ssl.PROTOCOL_TLS)**

Python documentation for reference: https://docs.python.org/3/library/ssl.html#ssl.PROTOCOL_TLSv1

**Comment by xorrior** [comment]
This has already been fixed in the master branch. https://github.com/EmpireProject/Empire/blob/master/empire#L1223

**Comment by crazyrat-software** [comment]
This is not fixed. The current master branch is using obsolete configuration of TLS protocol with version. Please refer to: https://docs.python.org/3/library/ssl.html#ssl.PROTOCOL_TLSv1

Fix should have only "**PROTOCOL_TLS**" which will negotiate best version between server and client.
