### ISSUE TITLE
Proxy settings are not taken into account while generating launcher

### ISSUE THREAD

**Issue by nikaiw** [EmpireProject/Empire#907]
## Empire Version
2.4 release

## OS Information (Linux flavor, Python version)
Ubuntu 16.04, python 2.7.12

## Expected behavior and description of the error

When generating a launcher from the HTTP listener menu, the Proxy settings are not taken into account leading to the value always being "default". I believe this could also be the case when generating from the stager menu and could affect other settings from the generation.

From what I see the callstack is the following:

do_launcher() called in Empire/lib/common/empire.py
generate() called in Empire/lib/stagers/multi/launcher.py
generate_launcher() called in Empire/lib/common/stagers.py
generate_launcher called in Empire/lib/listeners/http.py

I could fix this bug with the following modification in do_launcher:
```        try:
            # set the listener value for the launcher
            stager = self.mainMenu.stagers.stagers['multi/launcher']
            stager.options['Listener']['Value'] = self.listenerName
            stager.options['Language']['Value'] = parts[0]
            stager.options['Base64']['Value'] = "True"
            stager.options['Proxy']['Value'] = self.listener.options['Proxy']['Value']
            print stager.generate()
```
instead of 
```       try:
            # set the listener value for the launcher
            stager = self.mainMenu.stagers.stagers['multi/launcher']
            stager.options['Listener']['Value'] = self.listenerName
            stager.options['Language']['Value'] = parts[0]
            stager.options['Base64']['Value'] = "True"
            print stager.generate()
```
However I'm really doubtfull that is the best way/place to fix or which others option should be fixed.

**Comment by xorrior** [comment]
@nikaiw Here is a launcher generated from the stagers menu on the master branch (2.4). You can find the proxy (http://test.proxy.com:80) present in the generated launcher. Are you sure this is from the latest version? All stagers use the listener.generate_launcher method, so the proxy should be applied universally, if the option is set. 

![image](https://user-images.githubusercontent.com/9156069/34640533-2180739c-f2c2-11e7-8817-0446e540c6eb.png)

**Comment by nikaiw** [comment]
Hm the bug did not happen to me in the stager menu but in the listenner menu when using the "launcher powershell" command. I'm positive it was on master, I did a git pull before my tests. I'm about to check again from another machine.

**Comment by xorrior** [comment]
Fixed.

**Comment by nikaiw** [comment]
hm that didn't fix it for me the change would be good but the caller is actually "do_launcher" in the "ListenerMenu class" on line 3127 instead of the "ListenersMenu class" or maybe it had to be fixed in both function ?
I could dig, but I don't know enough empire architecture to quickly help at this point

**Comment by xorrior** [comment]
@nikaiw it should be fixed now.

**Comment by nikaiw** [comment]
Almost there, I get the following error "[!] Error generating launcher: global name 'listenerName' is not defined"
